logging:
  level:
    root: info
spring:
  mvc:
    path match:
      matching-strategy: path-pattern-parser
  application:
    name: qr-code-storage-service
    version: qr-code-storage-service-1.0
  liquibase:
    changeLog: classpath:db.changelog/db.changelog-master.yaml
    default-schema: public
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    parser:
      allow-single-quotes: true
  datasource:
    url: jdbc:postgresql://localhost:5432/qr_codes?stringtype=unspecified
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maxLifetime: 180000
      maximumPoolSize: 5

kafka:
  topics: ${KAFKA_TOPICS:medical_topic}
  bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:29092}
  group-id: ${GROUP_ID:medical_topic}
  concurrencyValue: ${CONCURRENCY_VALUE:1}
  key-deserializer: ${KAFKA_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
  value-deserializer: ${KAFKA_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}

feign:
  autoconfiguration:
    jackson:
      enabled: true

server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false