app:
  version: medical-service-1.0
  name: medical-service
spring:
  mvc:
    path match:
      matching-strategy: path-pattern-parser
  application:
    name: medical-service
  liquibase:
    changeLog: classpath:db.changelog/db.changelog-master.yaml
    default-schema: public
    enabled: true
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    parser:
      allow-single-quotes: true
  datasource:
    url: jdbc:postgresql://localhost:5432/medical?stringtype=unspecified
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maxLifetime: 180000
      maximumPoolSize: 5

external:
  kafka:
    bootstrap-server: ${BOOTSTRAP_SERVER:localhost:29092}
  client:
    person-service-client:
      base-url: ${BASE_URL:localhost:8081}
      service-name: ${SERVICE_NAME:person-service}

feign:
  autoconfiguration:
    jackson:
      enabled: true

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
